services:
  - type: web
    name: iot-sentinel
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PORT
        value: "10000"
      - key: RELOAD
        value: "false"
      - key: HOST
        value: "0.0.0.0"
      - key: RENDER
        value: "true"
    disk:
      name: iot-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    healthCheckPath: /health
    autoDeploy: true
